version: '3.8'

services:
  worker:
    build: .
    container_name: vinted-worker
    restart: always
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - SEARCH_QUERY=${SEARCH_QUERY}
      - MAX_PRICE=${MAX_PRICE}
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    # volumes:
    #   - ./logs:/app/logs

  redis:
    image: redis:alpine
    container_name: vinted-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
